---
name: ApexBridge Main Nightly Local Tests
on: # yamllint disable-line rule:truthy
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  apex-ci:
    name: ApexBridge CI
    uses: ./.github/workflows/apex-ci.yml
    with:
      e2e_apex_test: true
      e2e_skyline_test: false
      e2e_refund_test: true
      e2e_refund_skyline_bridge_test: false
      e2e_skyline_mba_test: false
      e2e_skyline_mint_test: false
      e2e_dynamic_validators_test: true
      apex_bridge_ref: main
      blade_apex_bridge_ref: develop
      e2e_apex_big_test: ${{ vars.RUN_E2E_BIG_TESTS }}
      e2e_apex_skip_redundant_tests: ${{ vars.SKIP_E2E_REDUNDANT_TESTS }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  notification_apex_nightly:
    name: ApexBridge Nightly Notification
    uses: ./.github/workflows/apex-notification-nightly.yml
    needs: apex-ci
    if: success() || failure()
    with:
      environment: nightly
      blade_apex_bridge_ref: develop
      build_blade_output: ${{ needs.apex-ci.outputs.build_blade }}
      lint_output: ${{ needs.apex-ci.outputs.lint }}
      unit_test_output: ${{ needs.apex-ci.outputs.unit_test }}
      e2e_apex_test_output: ${{ needs.apex-ci.outputs.e2e_apex_test }}
      e2e_apex_with_nexus_test_output: ${{ needs.apex-ci.outputs.e2e_apex_with_nexus_test }}
      e2e_refund_test_output: ${{ needs.apex-ci.outputs.e2e_refund_test }}
      e2e_dynamic_validators_test_output: ${{ needs.apex-ci.outputs.e2e_dynamic_validators_test }}
    secrets:
      APEX_SLACK_WEBHOOK_URL: ${{ secrets.APEX_SLACK_WEBHOOK_URL }}
