---
concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}-${{ inputs.apex_bridge_ref || 'main' }}
  cancel-in-progress: ${{ github.event_name != 'schedule' }}
name: ApexBridge CI
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - develop
      - feat/skyline
      - feat/skyline_refund
  pull_request:
  workflow_dispatch:
    inputs:
      lint:
        description: Lint
        type: boolean
        default: true
      unit_test:
        description: Unit Tests
        type: boolean
        default: true
      e2e_apex_test:
        description: E2E ApexBridge Tests
        type: boolean
        default: true
      e2e_skyline_test:
        description: E2E Skyline Tests
        type: boolean
        default: true
      e2e_refund_test:
        description: E2E Refund Tests
        type: boolean
        default: true
      e2e_refund_skyline_bridge_test:
        description: E2E Refund-Skyline Bridge Tests
        type: boolean
        default: false
      e2e_apex_big_test:
        description: E2E ApexBridge Big Tests
        type: boolean
        default: false
      e2e_skyline_mba_test:
        description: E2E Skyline MBA Tests
        type: boolean
        default: true
      e2e_apex_skip_redundant_tests:
        description: E2E ApexBridge Skip Redundant Tests
        type: boolean
        default: true
      apex_bridge_ref:
        description: The branch/commit from the Apex Bridge
        type: string
        default: feat/skyline
  workflow_call:
    inputs:
      lint:
        description: Lint
        type: boolean
        required: true
      unit_test:
        description: Unit Tests
        type: boolean
        required: true
      e2e_apex_test:
        description: E2E ApexBridge Tests
        type: boolean
        required: true
      e2e_skyline_test:
        description: E2E Skyline Tests
        type: boolean
        required: true
      e2e_refund_test:
        description: E2E Refund Tests
        type: boolean
        required: true
      e2e_refund_skyline_bridge_test:
        description: E2E Refund-Skyline Bridge Tests
        type: boolean
        required: true
      e2e_skyline_mba_test:
        description: E2E Skyline MBA Tests
        type: boolean
        required: true
      e2e_apex_big_test:
        description: E2E ApexBridge Big Tests
        type: string
        required: true
      e2e_apex_skip_redundant_tests:
        description: E2E ApexBridge Skip Redundant Tests
        type: string
        required: true
      apex_bridge_ref:
        description: The branch/commit from the Apex Bridge
        type: string
        required: true
      blade_apex_bridge_ref:
        description: The branch/commit from the Blade Apex Bridge
        type: string
        required: true
    outputs:
      build_blade:
        description: Build Blade output
        value: ${{ jobs.build_blade.outputs.workflow_output }}
      lint:
        description: Lint output
        value: ${{ jobs.lint.outputs.workflow_output }}
      unit_test:
        description: Unit Tests output
        value: ${{ jobs.unit_test.outputs.workflow_output }}
      e2e_apex_test:
        description: E2E ApexBridge Tests output
        value: ${{ jobs.e2e_apex_test.outputs.workflow_output }}
      e2e_skyline_test:
        description: E2E Skyline Tests output
        value: ${{ jobs.e2e_skyline_test.outputs.workflow_output }}
      e2e_refund_test:
        description: E2E Refund Tests output
        value: ${{ jobs.e2e_refund_test.outputs.workflow_output }}
      e2e_refund_skyline_bridge_test:
        description: E2E Refund-Skyline Bridge Tests output
        value: ${{ jobs.e2e_refund_skyline_bridge_test.outputs.workflow_output }}
      e2e_skyline_mba_test:
        description: E2E Skyline MBA Tests output
        value: ${{ jobs.e2e_skyline_mba_test.outputs.workflow_output }}
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  inputs_check:
    name: Inputs Check
    runs-on: ubuntu-latest
    outputs:
      skip_redundant_tests: ${{ steps.redudant_test_input_check.outputs.skip_redundant_tests }}
      apex_bridge_ref: ${{ steps.apex_bridge_ref_input_check.outputs.apex_bridge_ref }}
      blade_apex_bridge_ref: ${{ steps.blade_apex_bridge_ref_input_check.outputs.blade_apex_bridge_ref }}
    steps:
      - name: Redundant Tests Input Check
        id: redudant_test_input_check
        run: |
          if [[ "${{ inputs.e2e_apex_skip_redundant_tests }}" != "false" ]]; then
            echo "skip_redundant_tests=true" >> $GITHUB_OUTPUT
          else
            echo "skip_redundant_tests=false" >> $GITHUB_OUTPUT
          fi
      - name: Apex Bridge Ref Input Check
        id: apex_bridge_ref_input_check
        run: |
          if [[ "${{ inputs.apex_bridge_ref }}" == "" ]]; then
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              if [[ "${{ github.base_ref }}" == "feat/skyline" ]]; then
                echo "apex_bridge_ref=feat/skyline" >> $GITHUB_OUTPUT
              elif [[ "${{ github.base_ref }}" == "feat/skyline_refund" ]]; then
                echo "apex_bridge_ref=feat/skyline_refund" >> $GITHUB_OUTPUT
              else
                echo "apex_bridge_ref=main" >> $GITHUB_OUTPUT
              fi
            else
              if [[ "${{ github.ref }}" == "refs/heads/feat/skyline" ]]; then
                echo "apex_bridge_ref=feat/skyline" >> $GITHUB_OUTPUT
              elif [[ "${{ github.ref }}" == "refs/heads/feat/skyline_refund" ]]; then
                echo "apex_bridge_ref=feat/skyline_refund" >> $GITHUB_OUTPUT
              else
                echo "apex_bridge_ref=main" >> $GITHUB_OUTPUT
              fi
            fi
          else
            echo "apex_bridge_ref=${{ inputs.apex_bridge_ref }}" >> $GITHUB_OUTPUT
          fi
      - name: Blade Apex Bridge Ref Input Check
        id: blade_apex_bridge_ref_input_check
        run: |
          if [[ "${{ inputs.blade_apex_bridge_ref }}" == "" ]]; then
            echo "blade_apex_bridge_ref=${{ github.ref }}" >> $GITHUB_OUTPUT
          else
            echo "blade_apex_bridge_ref=${{ inputs.blade_apex_bridge_ref }}" >> $GITHUB_OUTPUT
          fi
  build_blade:
    name: Build Blade
    uses: ./.github/workflows/build.yml
    needs: inputs_check
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    needs: [inputs_check, build_blade]
    if: |
      inputs.lint || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/feat/skyline' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/feat/skyline_refund'))
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
  unit_test:
    name: Unit Tests
    uses: ./.github/workflows/unit-test.yml
    needs: [inputs_check, build_blade]
    if: |
      inputs.unit_test || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/feat/skyline' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/feat/skyline_refund'))
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
  e2e_apex_test:
    name: E2E ApexBridge Tests
    uses: ./.github/workflows/e2e-apex-test.yml
    needs: [inputs_check, build_blade]
    if: |
      inputs.e2e_apex_test || 
      github.event_name == 'pull_request'
    with:
      apex_bridge_ref: ${{ needs.inputs_check.outputs.apex_bridge_ref }}
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
      e2e_apex_big_test: ${{ inputs.e2e_apex_big_test || 'false' }}
      e2e_apex_skip_redundant_tests: ${{ needs.inputs_check.outputs.skip_redundant_tests }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_apex_test_push_develop:
    name: E2E ApexBridge Tests (push on develop branch)
    uses: ./.github/workflows/e2e-apex-test.yml
    needs: build_blade
    if: (github.event_name == 'push' && github.ref == 'refs/heads/develop')
    with:
      apex_bridge_ref: main
      blade_apex_bridge_ref: develop
      e2e_apex_big_test: false
      e2e_apex_skip_redundant_tests: false
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_apex_test_push_skyline:
    name: E2E ApexBridge Tests (push on feat/skyline branch)
    uses: ./.github/workflows/e2e-apex-test.yml
    needs: build_blade
    if: (github.event_name == 'push' && github.ref == 'refs/heads/feat/skyline')
    with:
      apex_bridge_ref: feat/skyline
      blade_apex_bridge_ref: feat/skyline
      e2e_apex_big_test: false
      e2e_apex_skip_redundant_tests: false
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_skyline_test:
    name: E2E Skyline Tests (Skyline only)
    uses: ./.github/workflows/e2e-skyline-test.yml
    needs: [inputs_check, build_blade]
    if: |
      inputs.e2e_skyline_test ||
      (github.event_name == 'pull_request' && (github.base_ref == 'feat/skyline' || github.base_ref == 'feat/skyline_refund'))
    with:
      apex_bridge_ref: ${{ needs.inputs_check.outputs.apex_bridge_ref }}
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
      e2e_apex_skip_redundant_tests: ${{ needs.inputs_check.outputs.skip_redundant_tests }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_skyline_test_push:
    name: E2E Skyline Tests (push on feat/skyline branch)
    uses: ./.github/workflows/e2e-skyline-test.yml
    needs: build_blade
    if: (github.event_name == 'push' && github.ref == 'refs/heads/feat/skyline')
    with:
      apex_bridge_ref: feat/skyline
      blade_apex_bridge_ref: feat/skyline
      e2e_apex_skip_redundant_tests: false
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_skyline_mba_test:
    name: E2E Skyline MBA Tests
    uses: ./.github/workflows/e2e-skyline-mba-test.yml
    needs: [inputs_check, build_blade]
    if: |
      inputs.e2e_skyline_mba_test ||
      (github.event_name == 'pull_request' && github.base_ref == 'feat/skyline')
    with:
      apex_bridge_ref: ${{ needs.inputs_check.outputs.apex_bridge_ref }}
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
      e2e_apex_skip_redundant_tests: ${{ needs.inputs_check.outputs.skip_redundant_tests }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_skyline_mba_test_push:
    name: E2E Skyline MBA Tests (push on feat/skyline branch)
    uses: ./.github/workflows/e2e-skyline-mba-test.yml
    needs: build_blade
    if: (github.event_name == 'push' && github.ref == 'refs/heads/feat/skyline')
    with:
      apex_bridge_ref: feat/skyline
      blade_apex_bridge_ref: feat/skyline
      e2e_apex_skip_redundant_tests: false
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_refund_test:
    name: E2E Refund Tests
    uses: ./.github/workflows/e2e-refund-test.yml
    needs: [inputs_check, build_blade]
    if: |
      inputs.e2e_refund_test ||
      (github.event_name == 'pull_request' && github.base_ref == 'feat/skyline_refund')
    with:
      apex_bridge_ref: ${{ needs.inputs_check.outputs.apex_bridge_ref }}
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
      e2e_apex_skip_redundant_tests: ${{ needs.inputs_check.outputs.skip_redundant_tests }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_refund_test_push:
    name: E2E Refund Tests (push on develop branch)
    uses: ./.github/workflows/e2e-refund-test.yml
    needs: build_blade
    if: (github.event_name == 'push' && github.ref == 'refs/heads/develop')
    with:
      apex_bridge_ref: main
      blade_apex_bridge_ref: develop
      e2e_apex_skip_redundant_tests: false
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_refund_skyline_bridge_test:
    name: E2E Refund-Skyline Bridge Tests
    uses: ./.github/workflows/e2e-refund-skyline-bridge-test.yml
    needs: [inputs_check, build_blade]
    if: |
      inputs.e2e_refund_skyline_bridge_test ||
      (github.event_name == 'pull_request' && github.base_ref == 'feat/skyline_refund')
    with:
      apex_bridge_ref: ${{ needs.inputs_check.outputs.apex_bridge_ref }}
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
      e2e_apex_skip_redundant_tests: ${{ needs.inputs_check.outputs.skip_redundant_tests }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_refund_skyline_bridge_test_push:
    name: E2E Refund-Skyline Bridge Tests (push on feat/skyline_refund branch)
    uses: ./.github/workflows/e2e-refund-skyline-bridge-test.yml
    needs: build_blade
    if: (github.event_name == 'push' && github.ref == 'refs/heads/feat/skyline_refund')
    with:
      apex_bridge_ref: feat/skyline_refund
      blade_apex_bridge_ref: feat/skyline_refund
      e2e_apex_skip_redundant_tests: false
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
