---
name: ApexBridge CI
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:
    inputs:
      build_blade:
        description: Build Blade
        type: boolean
        default: true
      lint:
        description: Lint
        type: boolean
        default: true
      unit_test:
        description: Unit Tests
        type: boolean
        default: true
      e2e_polybft_test:
        description: E2E PolyBFT Tests
        type: boolean
        default: true
      e2e_apex_test:
        description: E2E ApexBridge Tests
        type: boolean
        default: true
      e2e_apex_big_test:
        description: E2E ApexBridge Big Tests
        type: boolean
        default: true
      e2e_apex_skip_redundant_tests:
        description: E2E ApexBridge Skip Redundant Tests
        type: boolean
        default: true
  workflow_call:
    inputs:
      build_blade:
        description: Build Blade
        type: boolean
        required: true
      lint:
        description: Lint
        type: boolean
        required: true
      unit_test:
        description: Unit Tests
        type: boolean
        required: true
      e2e_polybft_test:
        description: E2E PolyBFT Tests
        type: boolean
        required: true
      e2e_apex_test:
        description: E2E ApexBridge Tests
        type: boolean
        required: true
      e2e_apex_big_test:
        description: E2E ApexBridge Big Tests
        type: string
        required: true
      e2e_apex_skip_redundant_tests:
        description: E2E ApexBridge Skip Redundant Tests
        type: string
        required: true
    outputs:
      build_blade:
        description: Build Blade output
        value: ${{ jobs.build_blade.outputs.workflow_output }}
      lint:
        description: Lint output
        value: ${{ jobs.lint.outputs.workflow_output }}
      unit_test:
        description: Unit Tests output
        value: ${{ jobs.unit_test.outputs.workflow_output }}
      e2e_polybft_test:
        description: E2E PolyBFT Tests output
        value: ${{ jobs.e2e_polybft_test.outputs.workflow_output }}
      e2e_apex_test:
        description: E2E ApexBridge Tests output
        value: ${{ jobs.e2e_apex_test.outputs.workflow_output }}
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  build_blade:
    name: Build Blade
    uses: ./.github/workflows/build.yml
    if: |
      inputs.build_blade || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    needs: build_blade
    if: |
      inputs.lint || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
  unit_test:
    name: Unit Tests
    uses: ./.github/workflows/unit-test.yml
    needs: build_blade
    if: |
      inputs.unit_test || 
      github.event_name == 'pull_request' || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
  e2e_polybft_test:
    name: E2E PolyBFT Tests
    uses: ./.github/workflows/e2e-polybft-test.yml
    needs: build_blade
    if: |
      inputs.e2e_polybft_test || 
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_apex_test:
    name: E2E ApexBridge Tests
    uses: ./.github/workflows/e2e-apex-test.yml
    needs: build_blade
    if: |
      inputs.e2e_apex_test || 
      github.event_name == 'pull_request'
    with:
      e2e_apex_big_test: ${{ inputs.e2e_apex_big_test || 'false' }}
      e2e_apex_skip_redundant_tests: ${{ inputs.e2e_apex_skip_redundant_tests || 'true' }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  e2e_apex_test_push:
    name: E2E ApexBridge Tests (push on main/develop branch)
    uses: ./.github/workflows/e2e-apex-test.yml
    needs: build_blade
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'))
    with:
      e2e_apex_big_test: true
      e2e_apex_skip_redundant_tests: false
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
