---
name: Dynamic Validators Nightly Tests
on: # yamllint disable-line rule:truthy
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '15 6 * * *'
  workflow_dispatch:

jobs:
  apex-ci:
    name: ApexBridge CI
    uses: ./.github/workflows/apex-ci.yml
    with:
      e2e_apex_test: false
      e2e_skyline_test: false
      e2e_refund_test: false
      e2e_refund_skyline_bridge_test: false
      e2e_skyline_mba_test: false
      e2e_skyline_mint_test: false
      e2e_dynamic_validators_test: true
      apex_bridge_ref: feat/validator_set_2
      blade_apex_bridge_ref: dynamic-validator-set
      e2e_apex_big_test: false
      e2e_apex_skip_redundant_tests: true
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  notification_dynamic_validators_nightly:
    name: Dynamic Validators Nightly Notification
    uses: ./.github/workflows/dynamic-validators-notification.yml
    needs: apex-ci
    if: success() || failure()
    with:
      blade_apex_bridge_ref: dynamic-validator-set
      build_blade_output: ${{ needs.apex-ci.outputs.build_blade }}
      lint_output: ${{ needs.apex-ci.outputs.lint }}
      unit_test_output: ${{ needs.apex-ci.outputs.unit_test }}
      e2e_dynamic_validators_test_output: ${{ needs.apex-ci.outputs.e2e_dynamic_validators_test }}
    secrets:
      APEX_SLACK_WEBHOOK_URL: ${{ secrets.APEX_SLACK_WEBHOOK_URL }}
