---
name: Skyline Nightly Local Tests
on: # yamllint disable-line rule:truthy
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  skyline_ci:
    name: Skyline CI
    uses: ./.github/workflows/apex-ci.yml
    with:
      lint: true
      unit_test: true
      e2e_apex_test: true
      e2e_skyline_test: true
      e2e_refund_test: false
      e2e_refund_skyline_bridge_test: false
      e2e_skyline_mba_test: true
      e2e_dynamic_validators_test: false
      apex_bridge_ref: feat/skyline
      blade_apex_bridge_ref: feat/skyline
      e2e_apex_big_test: ${{ vars.RUN_E2E_BIG_TESTS }}
      e2e_apex_skip_redundant_tests: ${{ vars.SKIP_E2E_REDUNDANT_TESTS }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  notification_skyline_nightly:
    name: Skyline Nightly Notification
    uses: ./.github/workflows/skyline-notification-nightly.yml
    needs: skyline_ci
    if: success() || failure()
    with:
      environment: nightly
      blade_apex_bridge_ref: feat/skyline
      build_blade_output: ${{ needs.skyline_ci.outputs.build_blade }}
      lint_output: ${{ needs.skyline_ci.outputs.lint }}
      unit_test_output: ${{ needs.skyline_ci.outputs.unit_test }}
      e2e_apex_test_output: ${{ needs.skyline_ci.outputs.e2e_apex_test }}
      e2e_skyline_test_output: ${{ needs.skyline_ci.outputs.e2e_skyline_test }}
      e2e_skyline_mba_test_output: ${{ needs.skyline_ci.outputs.e2e_skyline_mba_test }}
    secrets:
      APEX_SLACK_WEBHOOK_URL: ${{ secrets.APEX_SLACK_WEBHOOK_URL }}
