---
name: Apex Bridge Internal/Partner Skyline Testnet
on: # yamllint disable-line rule:truthy
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 22 * * *'
  workflow_dispatch:
    inputs:
      blade_apex_bridge_ref:
        description: The branch/commit from the Blade Apex Bridge
        type: string
        required: true
      run_blade_apex_bridge_internal:
        description: Run E2E Tests on Internal Testnet
        type: boolean
        default: true
      notification:
        description: Notification
        type: boolean
        default: true

jobs:
  inputs_check:
    name: Inputs Check
    runs-on: ubuntu-latest
    outputs:
      run_blade_apex_bridge_internal: ${{ steps.internal_input_check.outputs.run_blade_apex_bridge_internal }}
      blade_apex_bridge_ref: ${{ steps.blade_apex_bridge_ref_input_check.outputs.blade_apex_bridge_ref }}
      notification: ${{ steps.notification_input_check.outputs.notification }}
    steps:
      - name: Internal Input Check
        id: internal_input_check
        run: |
          if [[ "${{ inputs.run_blade_apex_bridge_internal }}" != "false" ]]; then
            echo "run_blade_apex_bridge_internal=true" >> $GITHUB_OUTPUT
          else
            echo "run_blade_apex_bridge_internal=false" >> $GITHUB_OUTPUT
          fi
      - name: Blade Apex Bridge Ref Input Check
        id: blade_apex_bridge_ref_input_check
        run: |
          if [[ "${{ inputs.blade_apex_bridge_ref }}" == "" ]]; then
            echo "blade_apex_bridge_ref=feat/skyline" >> $GITHUB_OUTPUT
          else
            echo "blade_apex_bridge_ref=${{ inputs.blade_apex_bridge_ref }}" >> $GITHUB_OUTPUT
          fi
      - name: Notification Input Check
        id: notification_input_check
        run: |
          if [[ "${{ inputs.notification }}" != "false" ]]; then
            echo "notification=true" >> $GITHUB_OUTPUT
          else
            echo "notification=false" >> $GITHUB_OUTPUT
          fi
  build_blade:
    name: Build Blade
    uses: ./.github/workflows/build.yml
    needs: inputs_check
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    needs: [inputs_check, build_blade]
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
  e2e_apex_internal_testnet_test:
    name: E2E Apex Bridge Internal Testnet Tests
    uses: ./.github/workflows/skyline-e2e-testnet-test.yml
    needs: [inputs_check, build_blade]
    if: needs.inputs_check.outputs.run_blade_apex_bridge_internal == 'true'
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
      blade_apex_bridge_version: internal
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      TESTNET_SKYLINE_BRIDGING_API_KEY: ${{ secrets.TESTNET_SKYLINE_BRIDGING_API_KEY }}
      SKYLINE_E2E_TESTNET_WALLET_KEYS_CONTENT: ${{ secrets.SKYLINE_E2E_TESTNET_WALLET_KEYS_CONTENT }}
  notification_apex_testnet:
    name: Apex Bridge Testnet Notification
    uses: ./.github/workflows/skyline-notification-testnet.yml
    needs: [inputs_check, build_blade, lint, e2e_apex_internal_testnet_test]
    if: needs.inputs_check.outputs.notification == 'true' && !cancelled()
    with:
      blade_apex_bridge_ref: ${{ needs.inputs_check.outputs.blade_apex_bridge_ref }}
      build_blade_output: ${{ needs.build_blade.outputs.workflow_output }}
      lint_output: ${{ needs.lint.outputs.workflow_output }}
      e2e_apex_internal_testnet_test_output: ${{ needs.e2e_apex_internal_testnet_test.outputs.workflow_output }}
    secrets:
      APEX_SLACK_WEBHOOK_URL: ${{ secrets.APEX_SLACK_WEBHOOK_URL }}
